### ISSUE TITLE
不错的项目，为什么不继续呢？

### ISSUE THREAD

**Issue by wzlee** [bastarder/vue-endless-h5-game#2]

**Comment by bastarder** [comment]
因为当初写这个游戏的时候初衷是为了学习Vue,然后锻炼一下思维,我把我想要的功能都基本已经实现了,游戏本身差的只是 数据而已, 我本没有想把游戏发出去的意思, 我自己也不擅长去完成那些平衡游戏数据, 所以就放在这当作入门vue的例子了~
